version: "3.8"

services:
    baileys-api:
        container_name: baileys-api
        build:
            context: .
            dockerfile: ./docker/Dockerfile.dev
        volumes:
            - ".:/app"
            - /app/node_modules
            - prisma:/prisma
        ports:
            - "${DOCKER_PORT}:3000"
volumes:
    postgres_data:
    prisma:
