version: "3.8"
services:
    baileys-db:
        image: postgres:15-alpine
        container_name: baileys-db
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - wpp-net

    baileys-api:
        container_name: baileys-api
        build:
            context: .
            dockerfile: ./docker/Dockerfile.prod
        restart: unless-stopped
        environment:
            NODE_ENV: production
            DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@baileys-db:5432/${POSTGRES_DB}
        depends_on:
            baileys-db:
                condition: service_healthy
        networks:
            - wpp-net
        ports:
            - "${API_PORT}:3000"

volumes:
    postgres_data:
        name: baileys_postgres_data

networks:
    wpp-net:
        driver: bridge
