version: "3.8"
services:
    whatsapp-api:
        container_name: whatsapp-api
        build:
            context: .
            dockerfile: ./docker/Dockerfile.prod
        restart: unless-stopped
        ports:
            - "${DOCKER_PORT}:3000"
