FROM node:20-alpine AS builder

WORKDIR /app

RUN apk update && apk add --no-cache openssl

COPY package*.json pnpm-lock.yaml ./

RUN npm i -g pnpm && pnpm install --quiet

RUN pnpm exec prisma migrate

COPY . .

EXPOSE 3000

CMD ["sh", "-c", "pnpm run db:deploy && pnpm run dev"]
