FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json pnpm-lock.yaml ./

RUN corepack enable && pnpm install --quiet

RUN pnpm exec prisma migrate

COPY . .

EXPOSE 3000

CMD [ "pnpm", "run", "dev" ]
